boto3-py new package to replace/update boto-py
fink/fink-distributions pull request #1152
Opened 2024-07-06 18:00 UTC by sth0

Older boto-py has been split into two utilities.  boto3-py depends on botocore-py ( PR #1151 ).  The boto3-py codes has no testing phase.

2024-07-23 11:20 UTC, nieder requested changes
No py311 just yet.

2024-07-23 11:24 UTC, nieder commented
The older boto-py had a bunch of utilities in %p/bin. These are now gone from botocore and boto3. Is there another package that has them or are they deprecated. Just curiosity, doesn't affect getting this in.

2024-07-31 01:01 UTC, sth0 commented
Removed ref to python 3.11 per suggestion.  I do not see any command line boto utilities in this package.  The old boto should "install along side" according to the documentation but that API is deprecated.  I can see where the boto utilities are useful but I don't see a way to install them.

2024-08-01 10:04 UTC, nieder approved these changes

2024-08-01 10:04 UTC, merged