Cran 20210330
fink/fink-distributions pull request #753
Opened 2021-03-30 04:46 UTC by babayoshihiko

New upstream versions of CRAN pacakges.

2021-03-31 11:07 UTC, nieder requested changes
Looks OK (but untested) after the 2 needed fixes to magick and vgam

2021-03-31 11:07 UTC, nieder commented on 10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-vgam-r.info
> +  1.1-5             >= 3.5.0
This says 1.1-5 is for R >= 3.5.0, but cran-vgam-r.info still shows it available for R-3.4 in `Type` field.

2021-04-01 08:47 UTC, babayoshihiko commented
FIxed the errors.

2021-04-01 11:51 UTC, nieder approved these changes

2021-04-01 11:51 UTC, merged