Cran 20210404
fink/fink-distributions pull request #767
Opened 2021-04-04 02:08 UTC by babayoshihiko

Regular updates.

2021-04-16 01:41 UTC, babayoshihiko commented
Can anyone review and merge?

2021-04-16 09:11 UTC, nieder requested changes

2021-04-21 23:31 UTC, babayoshihiko commented on 10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-rappdirs-r.info
> +Info2: <<
Added libgettext8 to rappdirs.

2021-04-22 01:21 UTC, nieder approved these changes

2021-04-22 01:21 UTC, merged