Cran 20210507
fink/fink-distributions pull request #784
Opened 2021-05-07 07:01 UTC by babayoshihiko

Regular CRAN updates, but

libcoin had missing Dep/BuildDep, and thus was fixed with a new revision number.
mice does not build for R 3.4 or earlier.
rgl now is >= 3.3.0.

2021-05-21 03:22 UTC, babayoshihiko commented
Added a missing BDep to cran-mice-*.

2021-05-21 11:26 UTC, nieder requested changes

2021-05-21 11:26 UTC, nieder commented on 10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-libcoin-r.info
>  Type: rversion (3.6 3.5 3.4)
CRAN libcoin page says it's for >= 3.4, so `DescPackaging` field should be adjusted.

2021-05-21 20:57 UTC, babayoshihiko commented on 10.9-libcxx/stable/main/finkinfo/libs/rmods/cran-libcoin-r.info
>  Type: rversion (3.6 3.5 3.4)
Fixed DescPackaging in libcoin.

2021-05-22 01:24 UTC, nieder approved these changes

2021-05-22 01:24 UTC, merged